version: '3'

services:
  aesm:
    image: cashmaney/aesm
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy

  bootstrap:
    image: cashmaney/enigma-sgx-bootstrap
    container_name: bootstrap
    depends_on:
      - aesm
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/enigmacli:/root/enigmacli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
    expose:
      - 26656
      - 26657

  node:
    image: cashmaney/enigma-sgx-node
    depends_on:
      - bootstrap
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/enigmacli:/root/enigmacli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy