[package]
name = "wasmi-runtime"
version = "0.1.0"
authors = ["Reuven Podmazo <reuven@enigma.co>"]
edition = "2018"
description = "An enclave running wasmi, to be used by cosmwasm-sgx-vm"

[lib]
name = "wasmi_runtime_enclave"
crate-type = ["staticlib"]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[features]
default = ["SGX_MODE_SW"]
SGX_MODE_SW = []
SGX_MODE_HW = []
production = ["SGX_MODE_HW", "log/max_level_warn", "log/release_max_level_warn"]
build-protobuf = ["protoc-rust", "dirs"]
test = []

# This annotation is here to trick the IDE into showing us type information about this crate.
# we alwats compile to the "sgx" target, so this will always be false.
# when compiling to the "sgx" target, we pull this from the target root with an "extern crate" directive
[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = [
    "backtrace"
] }

[dependencies]
sgx_tse = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_rand = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_trts = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tseal = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tcrypto = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
aes-siv = { git = "https://github.com/RustCrypto/AEADs", rev = "ff0118562dc56007099e9e19874855c9ecd75f90" }
enclave-ffi-types = { path = "../enclave-ffi-types" }
pwasm-utils = { version = "0.12.0", default-features = false }
parity-wasm = { version = "0.42.0", default-features = false }
serde = { git = "https://github.com/mesalock-linux/serde-sgx", features = [
    "derive"
] }
serde_json = { git = "https://github.com/mesalock-linux/serde-json-sgx" }
base64 = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rust-base64-sgx" }
ctor = "0.1.13"
schemars = "0.8.1"
bech32 = "0.7.2"
derive_more = "0.99"
sha2 = "0.8.1"
ring = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5" }
secp256k1 = "0.20.1"
# for attestation
chrono = { git = "https://github.com/mesalock-linux/chrono-sgx" }
num-bigint = { git = "https://github.com/mesalock-linux/num-bigint-sgx" }
uuid = "0.8.1"
httparse = { version = "1.3", default-features = false }
itertools = { version = "0.8", default-features = false, features = [] }
bit-vec = { version = "0.6", default-features = false }
lazy_static = "1.4"
# x25519-dalek = { version = "0.6", default-features = false, features = ["u64_backend"] }
hex = "0.4.2"
ripemd160 = "0.9.1"
log = "0.4.8"
lru = { version = "0.6", default-features = false }
protobuf = "2.22.0"

[dependencies.x25519-dalek]
version = "1.1.1"
git = "https://github.com/enigmampc/x25519-dalek"
rev = "ad1a39a848f621ca412ff8a1faf5ffc137f69954"
default-features = false
features = ["u64_backend"]

[patch.crates-io]
rand_core = { git = "https://github.com/mesalock-linux/rand-sgx", default-features = false, features = [
    "mesalock_sgx"
] }

[dependencies.prost]
git = "https://github.com/mesalock-linux/prost-sgx"
rev = "sgx_1.1.3"
default-features = false
features = ["prost-derive"]

[dependencies.wasmi]
git = "https://github.com/paritytech/wasmi"
rev = "84d2764594d80425373bf4949a58fa3df3d624c3"
default-features = false
features = ["core"]

[dependencies.base58]
git = "https://github.com/mesalock-linux/rust-base58-sgx"
package = "rust-base58"
rev = "sgx_1.1.3"

[dependencies.webpki]
git = "https://github.com/mesalock-linux/webpki"
branch = "mesalock_sgx"

[dependencies.webpki-roots]
git = "https://github.com/mesalock-linux/webpki-roots"
rev = "sgx_1.1.3"

[dependencies.yasna]
git = "https://github.com/mesalock-linux/yasna.rs-sgx"
rev = "sgx_1.1.3"
default-features = false
features = ["bit-vec", "num-bigint", "chrono", "mesalock_sgx"]

[dependencies.rustls]
git = "https://github.com/mesalock-linux/rustls"
rev = "sgx_1.1.3"
default-features = false
features = ["dangerous_configuration", "mesalock_sgx"]

[dev-dependencies]
sgx_edl = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[build-dependencies]
protoc-rust = { version = "2.0", optional = true }
dirs = { version = "3.0", optional = true }
