version: "3.9"
services:
  localsecret-1:
    image: "ghcr.io/scrtlabs/localsecret:v0.0.0"
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
      - "9091:9091"
      - "1317:1316"
      # faucet
      - "5000:5000"
    environment:
      LOG_LEVEL: "TRACE"
    #      SLEEP: "true"
    healthcheck:
      test: ["CMD-SHELL", "secretd status"]
      interval: 10s
      timeout: 5s
      retries: 5
  localsecret-2:
    image: "ghcr.io/scrtlabs/localsecret:v0.0.0"
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "36657:26657"
      - "36656:26656"
      - "9391:9091"
      - "9390:9090"
      - "2317:1316"
      # faucet
      - "5300:5000"
    environment:
      CHAINID: "secretdev-2"
      LOG_LEVEL: "TRACE"
    healthcheck:
      test: ["CMD-SHELL", "secretd status"]
      interval: 10s
      timeout: 5s
      retries: 5
  relayer:
    image: "hermes:v0.0.0"
    depends_on:
      localsecret-1:
        condition: service_healthy
      localsecret-2:
        condition: service_healthy
