version: '3'

services:
  aesm:
    image: fortanix/aesmd:2.13.103.1-1
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy

  base:
    image: tests-base-image
    depends_on:
      - aesm
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/secretd:/root/.secretd
      - /tmp/secretcli:/root/.secretcli
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "4g"

  bench:
    image: tests-base-image
    depends_on:
      - aesm
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/secretd:/root/.secretd
      - /tmp/secretcli:/root/.secretcli
    stdin_open: true
    entrypoint: ["/bin/bash", "go-tests-bench.sh"]
    tty: true
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"

  bootstrap:
    image: ci-enigma-sgx-bootstrap
    container_name: bootstrap
    depends_on:
      - aesm
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/secretd:/root/.secretd
      # - /tmp/secretcli:/root/.secretcli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
    expose:
      - 26656
      - 26657

  node:
    image: ci-enigma-sgx-node
    depends_on:
      - bootstrap
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/secretd:/tmp/.secretd
      # - /tmp/secretcli:/root/.secretcli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy

  enclave-test:
    image: rust-enclave-test
    depends_on:
      - aesm
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - /tmp/aesmd:/var/run/aesmd
      - /tmp/secretd:/tmp/.secretd
      - /tmp/secretcli:/root/.secretcli
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy
